### PR TITLE
chore: use `--call--module-type=all` instead of `--module`

### PR DESCRIPTION
**Pull request by ponkio-o**
Follow up following warning message:
CleanShot 2024-09-17 at 12 25 58

related: https://github.com/terraform-linters/tflint/pull/2036 / https://github.com/terraform-linters/tflint/pull/1951

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Thank you for your contribution!
We need to check the minimum required version of tflint for `--call--module-type=all`.

**Comment by ponkio-o** [comment]
> We need to check the minimum required version of tflint for --call--module-type=all.

That is certainly true!
But how to identify the version is troubling. I've come up with a way to parse result of `tflint --version` output, but there a better way?

**Comment by suzuki-shunsuke** [comment]
> But how to identify the version is troubling. I've come up with a way to parse result of tflint --version output, but there a better way?

I meant to clarify the minimum required version in the release note and the document.

**Comment by ponkio-o** [comment]
> I meant to clarify the minimum required version in the release note and the document.

That's sounds good. I updated the README. Would you like this?
https://github.com/suzuki-shunsuke/github-action-tflint/pull/1065/commits/9ee40ab9aeb5f12fabdd4024df4918dd15ff9d21

**Comment by suzuki-shunsuke** [comment]
Seems like the option was added at v0.50.0, not v0.51.0.

- https://github.com/terraform-linters/tflint/pull/1918
- https://github.com/terraform-linters/tflint/releases/tag/v0.50.0

**Comment by ponkio-o** [comment]
Sorry! Fixed it.
https://github.com/suzuki-shunsuke/github-action-tflint/pull/1065/commits/6fa8d64157d3beb46e5ad43c78bf1d4e60e1e6aa

**Comment by suzuki-shunsuke** [comment]
Sorry to keep you waiting.
I've released v1.1.1.

https://github.com/suzuki-shunsuke/github-action-tflint/releases/tag/v1.1.1

This release resolves the breaking change of this pull request.

- https://github.com/suzuki-shunsuke/github-action-tflint/pull/1145

**Pull request merged**
